import './assets/css/App.css';
import AppButton from './components/AppButton/AppButton';
import AppCard from './components/AppCard/AppCard';
import AppDropdown from './components/AppDropdown/AppDropdown';

let dummy = [
  {
    label: 'Option 1',
    value: 'option1'
  },
  {
    label: 'Option 2',
    value: 'option2'
  },
  {
    label: 'Option 3',
    value: 'option3'
  },
]

let movies = [
  {
    "EventGroup": "EG00071990",
    "EventTitle": "Notebook",
    "EventCode": "ET00093903",
    "EventImageCode": "notebook-2019-et00093903-10-01-2019-03-50-36",
    "EventImageUrl": "https://in.bmscdn.com/iedb/movies/images/mobile/thumbnail/medium/notebook-2019-et00093903-10-01-2019-03-50-36.jpg",
    "EventLanguage": "Hindi",
    "EventGenre": "Drama|Romance",
    "EventURL": "notebook",
    "EventName": "Notebook",
    "ShowDate": "29 Mar, 2019",
    "DispReleaseDate": "MARCH 29, 2019",
    "MonthID": "201903",
    "TrailerURL": "https://www.youtube.com/watch?v=SXYxOCLc9-c",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "U",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-02-22 19:34:18",
    "LanguageSequence": "1",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 8902,
      "dwtsCount": 15,
      "maybe": 0,
      "totalWTSCount": 8917,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [
      "AHD",
      "AHMED",
      "AND",
      "ALI",
      "ALLH",
      "AMRI",
      "AJMER",
      "AURA",
      "BANG",
      "BARA",
      "BEHA",
      "BELG",
      "BHAR",
      "BHNG",
      "BHIL",
      "BHOP",
      "BHUB",
      "BHILAI",
      "BOIS",
      "CHAN",
      "BURD",
      "CHD",
      "BHWD",
      "BILA",
      "BOKA",
      "BHWN",
      "BLRY",
      "CHEN",
      "COIM",
      "DEES",
      "CUTT",
      "DEH",
      "DHAN",
      "DAVA",
      "GDHAM",
      "GNAGAR",
      "DURGA",
      "DURG",
      "GUW",
      "GOA",
      "GULB",
      "HYD",
      "HLDI",
      "HWRH",
      "HALD",
      "HISR",
      "HUBL",
      "JAIP",
      "IND",
      "JALG",
      "JAM",
      "JODH",
      "JRSG",
      "JAMM",
      "KALG",
      "KANP",
      "KANK",
      "KHOP",
      "KOLH",
      "KGPR",
      "KOLK",
      "KOSA",
      "KOTA",
      "KRBA",
      "KURU",
      "LKPK",
      "LUCK",
      "LUDH",
      "MUMBAI",
      "MUDA",
      "MERT",
      "MANI",
      "NADI",
      "MUZA",
      "MYS",
      "NAGP",
      "NAND",
      "NASK",
      "NCR",
      "NVSR",
      "PALN",
      "PATA",
      "NMCH",
      "PATN",
      "PUNE",
      "RAJK",
      "RAIG",
      "RANC",
      "SANG",
      "ROH",
      "SOLA",
      "SILI",
      "SIKR",
      "SHLG",
      "SHIA",
      "SURT",
      "TRIV",
      "VAD",
      "UDAI",
      "VELL",
      "VIJA",
      "VAPI",
      "VIZA",
      "VLSD",
      "YAMU"
    ],
    "wtsCount": 9010,
    "dwtsCount": 16,
    "maybeCount": 0,
    "csCount": "9,026",
    "trailerUploadDate": 1550844258000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  {
    "EventGroup": "EG00045309",
    "EventTitle": "Junglee",
    "EventCode": "ET00065129",
    "EventImageCode": "junglee-et00065129-13-11-2017-03-34-14",
    "EventImageUrl": "https://in.bmscdn.com/iedb/movies/images/mobile/thumbnail/medium/junglee-et00065129-13-11-2017-03-34-14.jpg",
    "EventLanguage": "Hindi",
    "EventGenre": "Action|Adventure|Thriller",
    "EventURL": "junglee",
    "EventName": "Junglee",
    "ShowDate": "29 Mar, 2019",
    "DispReleaseDate": "MARCH 29, 2019",
    "MonthID": "201903",
    "TrailerURL": "https://www.youtube.com/watch?v=tcsJ-3GLDE4",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "UA",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-03-06 12:04:25",
    "LanguageSequence": "1",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 20056,
      "dwtsCount": 26,
      "maybe": 0,
      "totalWTSCount": 20082,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [
      "AHD",
      "AGRA",
      "ABOR",
      "AHMED",
      "AKOL",
      "AMRA",
      "AND",
      "ALI",
      "ALLH",
      "AMRI",
      "AJMER",
      "AMBI",
      "AMB",
      "AURA",
      "ANKV",
      "ASANSOL",
      "AZMG",
      "BADA",
      "BADD",
      "ARSI",
      "ATHN",
      "BANG",
      "BARA",
      "BEHA",
      "BARM",
      "BARG",
      "BARI",
      "BERP",
      "BASN",
      "BBCH",
      "BBHA",
      "BELG",
      "BHAN",
      "BHAA",
      "BHUS",
      "BHAR",
      "BHNG",
      "BHIL",
      "BHOP",
      "BHUB",
      "BHILAI",
      "BOIS",
      "CHAN",
      "BLPR",
      "BONI",
      "BURD",
      "CHD",
      "BHWD",
      "BIAR",
      "BLGT",
      "BLSR",
      "BONG",
      "BILA",
      "BKTH",
      "CHAM",
      "BOKA",
      "BHWN",
      "BLRY",
      "CHEN",
      "COIM",
      "CNSY",
      "CHOT",
      "COBE",
      "CHIN",
      "DHLE",
      "DEES",
      "DAKS",
      "DARJ",
      "DARH",
      "CUTT",
      "DEH",
      "DHAN",
      "DAVA",
      "GDHAM",
      "GNAGAR",
      "DURGA",
      "DHPR",
      "DHRI",
      "GDWR",
      "DHMT",
      "DONG",
      "DURG",
      "DMSL",
      "GAVT",
      "GUNT",
      "GRKP",
      "GTGN",
      "GUNA",
      "GUW",
      "GOA",
      "GULB",
      "HYD",
      "HALO",
      "HARR",
      "HLDI",
      "HOOG",
      "HWRH",
      "HOSH",
      "HAJI",
      "HALD",
      "HISR",
      "HUBL",
      "ICHL",
      "JAGJ",
      "JAIP",
      "IND",
      "ITAR",
      "JABL",
      "JAJP",
      "JALG",
      "JAMN",
      "JAM",
      "JPG",
      "JNSI",
      "JALA",
      "JODH",
      "JORT",
      "JAMM",
      "KARIM",
      "KARD",
      "KALG",
      "KALY",
      "KANP",
      "KASG",
      "KARE",
      "KANK",
      "KAWA",
      "KATI",
      "KCHA",
      "KHAM",
      "KHED",
      "KHOP",
      "KOLH",
      "KOCH",
      "KGPR",
      "KNWB",
      "KOLK",
      "KHAN",
      "KHCY",
      "KNGN",
      "KRHN",
      "KURN",
      "KOLM",
      "KOSA",
      "KOTA",
      "KPLI",
      "KUKS",
      "LAHA",
      "KRBA",
      "KURU",
      "KWAR",
      "MAHB",
      "MADU",
      "LKPK",
      "LUCK",
      "LUDH",
      "MADL",
      "MANE",
      "LOHA",
      "MUMBAI",
      "MUKM",
      "MUDA",
      "MATH",
      "MERT",
      "MORA",
      "MANW",
      "MORH",
      "MOTI",
      "MANI",
      "MLR",
      "MUVA",
      "MVLR",
      "NADI",
      "MUZ",
      "MUNI",
      "NAAM",
      "MUZA",
      "MYS",
      "NAGP",
      "NAND",
      "NASK",
      "NCR",
      "NAWA",
      "NAIN",
      "NAMI",
      "NIZA",
      "PALG",
      "PARB",
      "NKHT",
      "NVSR",
      "PALN",
      "PANH",
      "PATA",
      "PATH",
      "NMCH",
      "NZRA",
      "PATN",
      "PUNE",
      "POND",
      "PLKK",
      "PHAG",
      "PIPY",
      "PRKM",
      "PEND",
      "PLWL",
      "RATN",
      "RAJK",
      "RJLA",
      "PURU",
      "RANA",
      "RARA",
      "RATL",
      "RAAA",
      "RAIG",
      "RAIPUR",
      "RAXA",
      "RANC",
      "SANG",
      "SALM",
      "RNGJ",
      "RSRA",
      "SAML",
      "SAGA",
      "RWAA",
      "SAKT",
      "SARH",
      "RKES",
      "RUDP",
      "ROH",
      "SOLA",
      "SONG",
      "SILI",
      "SIKR",
      "SEMA",
      "SHAH",
      "SIMI",
      "SIL",
      "SMLA",
      "SHLG",
      "SHIA",
      "SURT",
      "SUND",
      "SVSG",
      "TKOT",
      "TIRP",
      "TIRU",
      "THOD",
      "THSR",
      "TINS",
      "TRIV",
      "VAD",
      "UDAI",
      "UJJN",
      "UDUP",
      "VELL",
      "VIJA",
      "VAPI",
      "VIZA",
      "VISN",
      "WAR",
      "WANI",
      "YAVA",
      "VLSD",
      "YAMU"
    ],
    "wtsCount": 20314,
    "dwtsCount": 26,
    "maybeCount": 0,
    "csCount": "20,340",
    "trailerUploadDate": 1551854065000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
]

function App() {
  return (
    <div className="App">
      Test
      <AppButton
        label="Click me"
      />
      <AppDropdown
        options={dummy}
      />
      <br />
      <br />
      <br />
      <div style={{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '25%',
        gap: '10px',
        padding: '10px'
      }}>
        {movies.map((movie, key) => {
          return (
            <AppCard
              key={key}
              data={movie}
              onClick={() => console.log('clicked', movie)}
            />
          )
        })}
      </div>
    </div>
  );
}

export default App;
